### ISSUE TITLE
kinect v2 particle tracker fails

### ISSUE THREAD

**Issue by balakumar-s** [bayesian-object-tracking/dbot_ros#3]
When using the particle tracker with kinect v2, the object starts moving towards the camera until it reaches the camera origin. Has anyone got it to work with kinect2?

**Comment by jbohg** [comment]
Turns out that there have been two issues with Kinect2.
1. Invalid depth values are encoded as 0.0 instead of NANs as was the case for Kinect1/XTION
2. The depth image encoding is 16U instead of 32F and it delivers in millimeters instead of meters (Thanks @amichlee!)

This had to be fixed in dbot and dbot_ros. Should be fixed now for 16.04. Couldn't test for 14.04 though. Would be great if someone who still runs 14.04 + KInect2 could test these fixes.
