### ISSUE TITLE
Did you try to send more than one object's information to an object tracking service to realize multi-objects tracking?

### ISSUE THREAD

**Issue by BIGJUN777** [bayesian-object-tracking/dbot_ros#8]
Thanks you for responding on my previous problem. For now, what I want to do are:  

1. Leverage some other methods to get information(id、initial pose...) of multiple objects;  
2. Send the information to the object tracking service to realize multi-objects tracking.  

The service_call script(~.py file) you provided seems can only track one object. If I want to proceed the second work described above, it seems I need to change the code to let the service get more message.I am going to do this. But I want to know did you do something like that before?Or do you have some good idea to share with me?

I am sorry maybe some sentence above are not smoothly. Hoping you can understand what I mean.    
Looking for your response.Thanks!

**Comment by honey-booboo** [comment]
You are right: the service we provide takes only one object as input. We never used it for more than one object. However, the tracker itself can handle several objects.

As you suggest, you could write and extended version of the [object tracker service node](https://github.com/bayesian-object-tracking/dbot_ros/blob/master/source/dbot_ros/tracker/object_tracker_service_node.cpp) that can handle several objects. 
- See [here](https://github.com/bayesian-object-tracking/dbot_ros/blob/eb2219730e3d5a46496d1bd8d46d391bc10081d2/source/dbot_ros/tracker/object_tracker_service_node.cpp#L44) how the `run` function takes only one pose as input, and then [here](https://github.com/bayesian-object-tracking/dbot_ros/blob/eb2219730e3d5a46496d1bd8d46d391bc10081d2/source/dbot_ros/tracker/object_tracker_service_node.cpp#L195) how the tracker is being initialized with a list containing that one pose only. You would have to extend this function to take as input several poses instead of only one. 
- The [ObjectResourceIdentifier](https://github.com/bayesian-object-tracking/dbot/blob/master/source/dbot/object_resource_identifier.h) should already be able to handle several meshes.

Don't forget to add the corresponding definitions of messages and services in the [dbot_ros_msgs](https://github.com/bayesian-object-tracking/dbot_ros_msgs) repo. 

PS. I'm sorry I can't be of more help. I was not the author of this code, so I don't know it in much detail. Please take these hints with a grain of salt.

**Comment by BIGJUN777** [comment]
Well, thanks for your useful advise.I will try something in the following days.  
Thanks again. Best!
